name: angular2_authentication_sample
version: 0.0.1-alpha.31
description: This is a sample that shows how to add authentication to an Angular 2 (ng2) app
homepage: https://github.com/rwl/angular2-authentication-sample
dependencies:
  angular2: ">=2.0.0-alpha.31 <3.0.0"
  browser: ">=0.10.0+2 <0.11.0"
  dart_jwt: ">=0.4.2 <0.5.0"
//transformers:
//- angular2:
//    entry_points: web/main.dart
authors:
- Martin Gontovnikas (http://gon.to) <martin@gon.to>
- PatrickJS <github@gdi2290.com>
license: MIT
repository:
  type: git
  url: https://github.com/rwl/angular2-authentication-sample.git
bugs:
  url: https://github.com/rwl/angular2-authentication-sample/issues
